# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Viscue < Formula
  desc "Your terminal password manager"
  homepage "https://github.com/rmscoal/viscue"
  version "0.1.2"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/rmscoal/viscue/releases/download/v0.1.2/viscue_0.1.2_darwin_amd64.tar.gz"
    sha256 "34f8758e5d39c068c65b990ac64332cbe0a24485c3c78d68af0add57e2408651"

    def install
      bin.install "viscue"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/rmscoal/viscue/releases/download/v0.1.2/viscue_0.1.2_darwin_arm64.tar.gz"
    sha256 "d98e9aa894987935a783ac72608a91063b9f90be5f387ef57ba6910d57619312"

    def install
      bin.install "viscue"
    end
  end
end
